-- ============================================================================
-- geoAtt 0004 — employees, and face templates as their own table
--
-- THE CHANGE THAT MATTERS IN THIS FILE
--
-- The old schema kept face_descriptor as a jsonb column on employees: 128
-- floats per enrolled pose, up to four poses, roughly 10 kB of JSON per person.
-- The HR dashboard then ran
--
--   supabase.from('employees').select('*')
--
-- with no column list, no limit and no caching. At 600 employees that is on the
-- order of 6 MB of face vectors serialised into every dashboard load, for data
-- the dashboard never renders.
--
-- Templates now live in their own table. The roster query cannot touch them by
-- accident, because they are not there to touch — the fix is structural rather
-- than a discipline that the next `select('*')` would undo.
-- ============================================================================

create table if not exists public.employees (
  id              uuid primary key default gen_random_uuid(),

  -- One employees row per profile. Nullable so HR can prepare a roster before
  -- the accounts exist, which is how CSV import works.
  user_id         uuid unique references public.profiles(id) on delete cascade,

  -- Human-facing code, EMP-0001. Generated by the sequence below.
  employee_code   text not null unique,

  -- Employment facts only. Name, email, phone and avatar live on profiles and
  -- are joined at read time — see 0002.
  department_id   uuid references public.departments(id) on delete set null,
  designation     text,
  joining_date    date,
  exit_date       date,
  status          public.employment_status not null default 'active',

  site_id         uuid references public.sites(id) on delete set null,
  shift_id        uuid references public.shifts(id) on delete set null,

  reward_points   integer not null default 0,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint employees_reward_points_non_negative check (reward_points >= 0),
  constraint employees_exit_after_joining check (
    exit_date is null or joining_date is null or exit_date >= joining_date
  )
);

-- The directory filters on both of these on every load, and neither was
-- indexed in the old schema.
create index if not exists employees_status_idx on public.employees (status);
create index if not exists employees_department_idx on public.employees (department_id);
create index if not exists employees_site_idx on public.employees (site_id);
create index if not exists employees_shift_idx on public.employees (shift_id);

drop trigger if exists employees_touch on public.employees;
create trigger employees_touch before update on public.employees
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Employee code sequence. EMP-0001, EMP-0002, ...
--
-- A sequence rather than max()+1: two concurrent CSV imports both reading the
-- maximum would allocate the same code and one would fail the unique index.
-- ---------------------------------------------------------------------------
create sequence if not exists public.employee_code_seq as bigint start 1;

create or replace function public.next_employee_code()
returns text
language sql
volatile
as $$
  select 'EMP-' || lpad(nextval('public.employee_code_seq')::text, 4, '0');
$$;

-- ---------------------------------------------------------------------------
-- face_templates — one row per enrolled pose.
--
-- Stored as a float array, never as a photograph: the numbers cannot be turned
-- back into an image, so there is no face library to leak. Attendance selfies
-- are separate, live in a private bucket, and are evidence rather than
-- identity.
--
-- One row per pose instead of one jsonb blob means a pose can be re-enrolled
-- or audited on its own, and the descriptor length can actually be constrained.
-- ---------------------------------------------------------------------------
create table if not exists public.face_templates (
  id            uuid primary key default gen_random_uuid(),
  employee_id   uuid not null references public.employees(id) on delete cascade,

  -- centre | left | right | up
  pose          text not null,

  -- 128 floats from face-api's faceRecognitionNet. The model is fixed by the
  -- data: descriptors from a different model are not comparable, so changing
  -- it means every employee re-enrols. Recorded here so that is a deliberate
  -- decision rather than a surprise.
  descriptor    double precision[] not null,
  model         text not null default 'face-api/faceRecognitionNet@1',

  enrolled_at   timestamptz not null default now(),

  constraint face_templates_pose_valid check (pose in ('centre', 'left', 'right', 'up')),
  constraint face_templates_descriptor_len check (array_length(descriptor, 1) = 128)
);

-- One template per pose per employee; re-enrolling a pose replaces it.
create unique index if not exists face_templates_employee_pose_key
  on public.face_templates (employee_id, pose);

create index if not exists face_templates_employee_idx
  on public.face_templates (employee_id);

-- ---------------------------------------------------------------------------
-- Enrolment attempts, tracked on the employee.
--
-- Face registration is one-shot by design: the template is the identity anchor
-- for every future check-in, so letting someone silently re-point it at
-- another face would defeat the whole control. A second registration needs an
-- explicit HR grant.
-- ---------------------------------------------------------------------------
alter table public.employees
  add column if not exists face_enroll_attempts integer not null default 0,
  add column if not exists face_enroll_granted_at timestamptz,
  add column if not exists face_enroll_granted_by uuid references public.profiles(id) on delete set null;

alter table public.employees
  drop constraint if exists employees_face_attempts_non_negative;
alter table public.employees
  add constraint employees_face_attempts_non_negative check (face_enroll_attempts >= 0);

-- Convenience: is this employee enrolled at all?
create or replace function public.employee_is_enrolled(target uuid)
returns boolean
language sql
stable
as $$
  select exists (select 1 from public.face_templates where employee_id = target);
$$;
